Repository bonitasoft/antora-detect-unused-media-extension, pull requests merged in 2025-02, with the labels that each got.

#6 feat: Detect media in partial
  src/index.js
  tests/detect-unused-media.test.js
Labels: enhancement

#9 ci: Update github actions with dependabot
  .github/dependabot.yml
Labels: github_actions

#10 fix: use convenient logger name
  src/index.js
Labels: bug
